services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      target: development
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - mynet

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mynet

  mysql:
    image: mysql:latest 
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin  
      MYSQL_DATABASE: publico 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynet
    restart: unless-stopped
networks:
  mynet: 
   driver: bridge
